import type { Exercise } from './types';

export const BUILTIN_EXERCISE_ID_PREFIX = 'builtin-exercise:';

interface BuiltInExerciseGroup {
  category: string;
  equipment: string;
  primary: string;
  secondary?: string[];
  names: string[];
}

const BUILTIN_GROUPS: BuiltInExerciseGroup[] = [
  {
    category: 'Klatka piersiowa',
    equipment: 'Sztanga / hantle / maszyna',
    primary: 'Klatka piersiowa',
    secondary: ['Triceps', 'Przednie barki'],
    names: [
      'Wyciskanie sztangi na ławce płaskiej',
      'Wyciskanie hantli na ławce płaskiej',
      'Wyciskanie sztangi na ławce skośnej dodatniej',
      'Wyciskanie hantli na ławce skośnej dodatniej',
      'Wyciskanie sztangi na ławce skośnej ujemnej',
      'Wyciskanie na maszynie siedząc',
      'Wyciskanie na maszynie Hammer',
      'Rozpiętki z hantlami',
      'Rozpiętki na bramie',
      'Rozpiętki na maszynie pec deck',
      'Pompki klasyczne',
      'Pompki z nogami na podwyższeniu',
      'Pompki na poręczach z akcentem na klatkę',
      'Pullover z hantlem',
      'Svend press',
    ],
  },
  {
    category: 'Plecy',
    equipment: 'Drążek / wyciąg / sztanga / hantle',
    primary: 'Plecy',
    secondary: ['Biceps', 'Tylne barki', 'Przedramiona'],
    names: [
      'Podciąganie nachwytem',
      'Podciąganie podchwytem',
      'Podciąganie neutralnym chwytem',
      'Ściąganie drążka wyciągu górnego',
      'Ściąganie drążka podchwytem',
      'Ściąganie jednorącz na wyciągu',
      'Wiosłowanie sztangą w opadzie',
      'Wiosłowanie hantlem jednorącz',
      'Wiosłowanie siedząc na wyciągu',
      'Wiosłowanie na maszynie',
      'Wiosłowanie półsztangą',
      'Seal row',
      'Chest supported row',
      'Face pull',
      'Prostowanie ramion na wyciągu stojąc',
      'Narciarz na wyciągu',
      'Martwy ciąg klasyczny',
      'Rack pull',
      'Good morning',
      'Superman',
    ],
  },
  {
    category: 'Barki',
    equipment: 'Sztanga / hantle / wyciąg / maszyna',
    primary: 'Barki',
    secondary: ['Triceps', 'Górna część pleców'],
    names: [
      'Wyciskanie żołnierskie',
      'Wyciskanie hantli nad głowę',
      'Wyciskanie na maszynie na barki',
      'Arnold press',
      'Push press',
      'Unoszenie hantli bokiem',
      'Unoszenie linki bokiem',
      'Unoszenie hantli przodem',
      'Odwrotne rozpiętki z hantlami',
      'Odwrotne rozpiętki na maszynie',
      'Wiosłowanie sztangą do brody',
      'High pull',
      'Y-raise na ławce',
      'Cuban press',
      'Rotacja zewnętrzna barku z gumą',
      'Scapular wall slide',
    ],
  },
  {
    category: 'Ramiona',
    equipment: 'Sztanga / hantle / wyciąg / poręcze',
    primary: 'Ramiona',
    secondary: ['Przedramiona', 'Barki'],
    names: [
      'Uginanie ramion ze sztangą',
      'Uginanie ramion z hantlami',
      'Uginanie młotkowe',
      'Uginanie na modlitewniku',
      'Uginanie na wyciągu dolnym',
      'Uginanie koncentracyjne',
      'Spider curl',
      'Incline dumbbell curl',
      'Zottman curl',
      'Reverse curl',
      'Wyprosty na wyciągu górnym',
      'Francuskie wyciskanie sztangi leżąc',
      'Francuskie wyciskanie hantla siedząc',
      'Prostowanie ramienia z hantlem w opadzie',
      'Wyciskanie wąskim chwytem',
      'Pompki na poręczach z akcentem na triceps',
      'Overhead triceps extension na wyciągu',
      'Prostowanie linki nad głową',
      'Uginanie nadgarstków podchwytem',
      'Uginanie nadgarstków nachwytem',
      'Spacer farmera',
      'Zwis na drążku',
    ],
  },
  {
    category: 'Nogi',
    equipment: 'Sztanga / hantle / maszyna',
    primary: 'Nogi',
    secondary: ['Pośladki', 'Core'],
    names: [
      'Przysiad ze sztangą na plecach',
      'Przysiad przedni',
      'Goblet squat',
      'Hack squat',
      'Przysiad bułgarski',
      'Wykroki chodzone',
      'Wykroki w miejscu',
      'Zakroki',
      'Step-up na podwyższenie',
      'Wyciskanie nóg na suwnicy',
      'Prostowanie nóg na maszynie',
      'Sissy squat',
      'Przysiad na jednej nodze do skrzyni',
      'Pistol squat',
      'Przysiad sumo',
      'Cossack squat',
      'Wall sit',
      'Przysiad z pauzą',
      'Przysiad tempo',
      'Spanish squat',
    ],
  },
  {
    category: 'Tył uda i pośladki',
    equipment: 'Sztanga / hantle / maszyna / guma',
    primary: 'Pośladki i dwugłowe uda',
    secondary: ['Dolne plecy', 'Core'],
    names: [
      'Martwy ciąg rumuński',
      'Martwy ciąg na prostych nogach',
      'Martwy ciąg sumo',
      'Hip thrust ze sztangą',
      'Glute bridge',
      'Glute bridge jednonóż',
      'Uginanie nóg leżąc',
      'Uginanie nóg siedząc',
      'Nordic hamstring curl',
      'Good morning z gumą',
      'Pull-through na wyciągu',
      'Cable kickback',
      'Odwodzenie biodra na maszynie',
      'Odwodzenie biodra z gumą',
      'Monster walk z gumą',
      'Clamshell',
      'Back extension',
      'Reverse hyperextension',
      'Kettlebell swing',
      'Single-leg RDL',
    ],
  },
  {
    category: 'Łydki',
    equipment: 'Maszyna / sztanga / hantle',
    primary: 'Łydki',
    secondary: ['Staw skokowy'],
    names: [
      'Wspięcia na palce stojąc',
      'Wspięcia na palce siedząc',
      'Wspięcia na palce na suwnicy',
      'Wspięcia jednonóż',
      'Donkey calf raise',
      'Tibialis raise',
      'Skakanka',
      'Pogo jumps',
    ],
  },
  {
    category: 'Core',
    equipment: 'Własna waga / linka / piłka',
    primary: 'Brzuch',
    secondary: ['Skośne brzucha', 'Dolne plecy'],
    names: [
      'Deska',
      'Deska boczna',
      'Dead bug',
      'Bird-dog',
      'Hollow body hold',
      'Mountain climber',
      'Unoszenie nóg w zwisie',
      'Unoszenie kolan w zwisie',
      'Cable crunch',
      'Spięcia brzucha',
      'Reverse crunch',
      'Russian twist',
      'Pallof press',
      'Rollout z kółkiem',
      'Rollout ze sztangą',
      'Woodchopper na wyciągu',
      'Suitcase carry',
      'Farmer carry jednostronny',
      'Toe touches',
      'V-up',
    ],
  },
  {
    category: 'Full body i moc',
    equipment: 'Sztanga / kettlebell / własna waga',
    primary: 'Całe ciało',
    secondary: ['Core', 'Nogi', 'Plecy'],
    names: [
      'Clean',
      'Power clean',
      'Hang clean',
      'Snatch',
      'Power snatch',
      'Clean and jerk',
      'Thruster',
      'Burpee',
      'Burpee box jump',
      'Man maker',
      'Kettlebell clean',
      'Kettlebell snatch',
      'Turkish get-up',
      'Sled push',
      'Sled pull',
      'Battle ropes',
      'Rzut piłką lekarską o ziemię',
      'Wall ball',
    ],
  },
  {
    category: 'Kalistenika',
    equipment: 'Własna waga / drążek / poręcze',
    primary: 'Całe ciało',
    secondary: ['Core', 'Ramiona'],
    names: [
      'Pompki diamentowe',
      'Pompki szerokie',
      'Pompki pike',
      'Handstand push-up',
      'Podciąganie australijskie',
      'Scapular pull-up',
      'Negatywne podciąganie',
      'Muscle-up',
      'L-sit',
      'Hollow rocks',
      'Dips na ławce',
      'Dips na kółkach',
      'Przysiad z wyskokiem',
      'Wykrok z wyskokiem',
      'Bear crawl',
      'Crab walk',
      'Inchworm',
      'Plank shoulder taps',
      'Archer push-up',
      'Archer pull-up',
    ],
  },
  {
    category: 'Bieganie i kondycja',
    equipment: 'Brak / teren / ergometr',
    primary: 'Kondycja',
    secondary: ['Nogi', 'Core'],
    names: [
      'Bieg spokojny',
      'Bieg regeneracyjny',
      'Bieg tempowy',
      'Długi bieg',
      'Interwały biegowe',
      'Podbiegi',
      'Sprinty',
      'Fartlek',
      'Marszobieg',
      'Rower stacjonarny',
      'Ergometr wioślarski',
      'Air bike',
      'SkiErg',
      'Orbitrek',
      'Trucht rozgrzewkowy',
    ],
  },
  {
    category: 'Mobilność i prehab',
    equipment: 'Własna waga / guma / wałek',
    primary: 'Mobilność',
    secondary: ['Stawy', 'Core'],
    names: [
      'Rotacje bioder 90/90',
      'World greatest stretch',
      'Cat-cow',
      'Child pose',
      'Thoracic rotation',
      'Open book',
      'Couch stretch',
      'Rozciąganie zginaczy bioder',
      'Rozciąganie dwugłowych uda',
      'Rozciąganie łydki przy ścianie',
      'Mobilizacja stawu skokowego knee-to-wall',
      'Mobilizacja nadgarstków',
      'Band pull-apart',
      'Face pull z gumą',
      'Terminal knee extension z gumą',
      'Spanish squat izometryczny',
      'Wall angels',
      'Foam rolling czworogłowych',
      'Foam rolling pasma biodrowo-piszczelowego',
      'Oddychanie przeponowe w leżeniu',
    ],
  },
];

const BUILTIN_CREATED_AT = '1970-01-01T00:00:00.000Z';

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function isBuiltInExerciseId(id: string | null | undefined): boolean {
  return Boolean(id?.startsWith(BUILTIN_EXERCISE_ID_PREFIX));
}

function toExercise(group: BuiltInExerciseGroup, name: string): Exercise {
  return {
    id: `${BUILTIN_EXERCISE_ID_PREFIX}${slugify(name)}`,
    user_id: 'builtin-catalog',
    sport_id: null,
    name,
    category: group.category,
    primary_muscle_group: group.primary,
    secondary_muscle_groups: group.secondary ?? null,
    equipment: group.equipment,
    notes: 'Wbudowany katalog referencyjny Rootine.',
    is_archived: false,
    created_at: BUILTIN_CREATED_AT,
    updated_at: BUILTIN_CREATED_AT,
    deleted_at: null,
  };
}

export const BUILTIN_EXERCISES: Exercise[] = BUILTIN_GROUPS.flatMap((group) =>
  group.names.map((name) => toExercise(group, name)),
);

export function mergeBuiltInExercises(exercises: Exercise[]): Exercise[] {
  const seenNames = new Set(exercises.map((exercise) => exercise.name.trim().toLocaleLowerCase('pl-PL')));
  const builtIns = BUILTIN_EXERCISES.filter((exercise) => !seenNames.has(exercise.name.trim().toLocaleLowerCase('pl-PL')));
  return [...exercises, ...builtIns];
}
